FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    sudo \
    ca-certificates \
    curl \
    gnupg \
    git \
    jq \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages ansible-core==2.17.0

RUN mkdir -p /etc/ansible
