---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    skip_reboot: true
    ubtu24stig_cat1: false
    ubtu24stig_cat2: true
    ubtu24stig_cat3: true
    ubtu24stig_install_cloud_init: true

  roles:
    - role: ..
      ubtu24stig_102000: false
      ubtu24stig_100030: false
      ubtu24stig_100040: false
